name: Automated review
 
on: [push]
 
jobs: 
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: npm updates
        run: npm i
 
#      - name: Run prettier check
#        run: npm run check
  build-container:
   runs-on: ubuntu-latest
   steps:
    - name: Build Container
      uses: docker/build-push-action@v6.18.0
